// Currículo A2 (Español → Inglés) · Unidades 7–12. Sigue la Metodología:
// alta frecuencia → frases → oraciones, en contexto, con las 4 habilidades.
// Gramática A2: pasado simple, futuro (going to / will), funciones de viaje,
// transaccional (restaurante/compras), descripción (presente continuo,
// comparativos/superlativos), salud + consejos (should) + present perfect intro.
//
// Cada unidad: 4 lecciones × 8 ítems (3 reading + 3 writing + 1 listening + 1
// speaking) → checkpoint toma 3R+3W+2L+2S. Formato idéntico a A1 (gen_a2.mjs
// valida contra el grader determinista antes de emitir SQL).

const R = (prompt, options, value) => ({ type: 'multiple_choice', skill: 'reading', prompt, payload: { options }, correct: { value } });
const M = (prompt, pairs) => ({ type: 'match', skill: 'reading', prompt, payload: { pairs: pairs.map(([en, es]) => ({ en, es })) }, correct: { pairs } });
const CZ = (prompt, text, value, accepted) => ({ type: 'cloze', skill: 'writing', prompt, payload: { text }, correct: { value, accepted: accepted || [value] } });
const TR = (source, value, accepted) => ({ type: 'translation', skill: 'writing', prompt: `Traduce: "${source}".`, payload: { source }, correct: { value, accepted: accepted || [value] } });
const WB = (prompt, tiles, sequence) => ({ type: 'word_bank', skill: 'writing', prompt, payload: { tiles }, correct: { value: sequence.join(' '), sequence } });
const RO = (prompt, value, tiles) => ({ type: 'reorder', skill: 'writing', prompt, payload: { tiles }, correct: { value } });
const L = (options, value) => ({ type: 'listening', skill: 'listening', prompt: 'Escucha y elige lo que oíste.', payload: { options, say: value }, correct: { value } });
const SP = (text) => ({ type: 'speaking_read_aloud', skill: 'speaking', prompt: 'Lee en voz alta:', payload: { text }, correct: { expected: text } });

export const UNITS = [
  // ── Unidad 7 — El pasado: lo que hice ─────────────────────────────────────
  {
    U: 7, title: 'El pasado: lo que hice', theme_color: '#5C8DEF', icon: 'history',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Demuestra el pasado simple: was/were, verbos regulares (-ed), irregulares (went, had, saw) y preguntas/negativos con did.',
    vocab: [
      { word: 'yesterday', translation: 'ayer', pos: 'adverb' },
      { word: 'last night', translation: 'anoche', pos: 'adverb' },
      { word: 'ago', translation: 'hace (tiempo)', pos: 'adverb' },
      { word: 'weekend', translation: 'fin de semana', pos: 'noun' },
      { word: 'went', translation: 'fue / fui (ir)', pos: 'verb' },
      { word: 'had', translation: 'tuvo / tenía (tener)', pos: 'verb' },
      { word: 'saw', translation: 'vio (ver)', pos: 'verb' },
      { word: 'ate', translation: 'comió (comer)', pos: 'verb' },
      { word: 'bought', translation: 'compró (comprar)', pos: 'verb' },
      { word: 'worked', translation: 'trabajó', pos: 'verb' },
      { word: 'played', translation: 'jugó', pos: 'verb' },
      { word: 'watched', translation: 'miró / vio', pos: 'verb' },
      { word: 'traveled', translation: 'viajó', pos: 'verb' },
      { word: 'did', translation: 'hizo (auxiliar de pasado)', pos: 'verb' },
    ],
    lessons: [
      {
        title: 'Ayer (was / were)', topic: 'past_to_be',
        description: 'was/were · yesterday, last night · "I was at home"',
        items: [
          M('Empareja cada palabra con su traducción.', [['yesterday', 'ayer'], ['last night', 'anoche'], ['ago', 'hace (tiempo)']]),
          R('Completa: "I ___ at home yesterday."', ['was', 'were', 'am'], 'was'),
          R('Completa: "They ___ happy."', ['was', 'were', 'is'], 'were'),
          CZ('Completa con el pasado de "to be": "She ___ tired last night."', 'She ___ tired last night.', 'was'),
          TR('Yo estaba en casa.', 'I was at home.', ['I was at home', 'I was home']),
          WB('Arma la frase: "Estábamos en la fiesta".', ['We', 'were', 'at', 'the', 'party', 'is'], ['We', 'were', 'at', 'the', 'party']),
          L(['We were late yesterday.', 'We are late today.', 'They were at home.'], 'We were late yesterday.'),
          SP('Yesterday I was very happy.'),
        ],
      },
      {
        title: 'Verbos regulares (-ed)', topic: 'regular_past',
        description: 'worked, played, watched, lived · "Yesterday I watched TV"',
        items: [
          M('Empareja el verbo en pasado con su traducción.', [['worked', 'trabajó'], ['played', 'jugó'], ['watched', 'miró']]),
          R('Completa: "Yesterday I ___ TV."', ['watched', 'watch', 'watches'], 'watched'),
          R('El pasado de "play" es…', ['played', 'plaied', 'play'], 'played'),
          CZ('Completa: "They ___ football last weekend."', 'They ___ football last weekend.', 'played'),
          TR('Trabajé ayer.', 'I worked yesterday.', ['I worked yesterday']),
          RO('Ordena las palabras: "Ella vio una película".', 'She watched a movie', ['movie', 'She', 'a', 'watched']),
          L(['I cooked dinner last night.', 'I cook dinner every day.', 'She watched a movie.'], 'I cooked dinner last night.'),
          SP('Last weekend I played with my friends.'),
        ],
      },
      {
        title: 'Verbos irregulares (went, had, saw)', topic: 'irregular_past',
        description: 'went, had, saw, ate, bought · "I went to the park"',
        items: [
          M('Empareja el verbo en pasado con su traducción.', [['went', 'fue'], ['had', 'tuvo'], ['saw', 'vio']]),
          R('El pasado de "go" es…', ['went', 'goed', 'gone'], 'went'),
          R('Completa: "Yesterday I ___ my friend."', ['saw', 'see', 'seen'], 'saw'),
          CZ('Completa: "We ___ a great time."', 'We ___ a great time.', 'had'),
          TR('Comí pizza.', 'I ate pizza.', ['I ate pizza']),
          WB('Arma la frase: "Fui al parque".', ['I', 'went', 'to', 'the', 'park', 'go'], ['I', 'went', 'to', 'the', 'park']),
          L(['She bought a new phone.', 'She buys a new phone.', 'He sold his car.'], 'She bought a new phone.'),
          SP('Last year I went to the beach.'),
        ],
      },
      {
        title: 'Preguntas y negativos (did / didn\'t)', topic: 'past_questions',
        description: 'Did you…? · I didn\'t… · "Did you see the movie?"',
        items: [
          R('Completa: "___ you go to school?"', ['Did', 'Do', 'Was'], 'Did'),
          R('Completa: "I ___ go yesterday."', ["didn't", "don't", "wasn't"], "didn't"),
          R('"Did you eat?" es una pregunta en…', ['pasado', 'presente', 'futuro'], 'pasado'),
          CZ('Completa el negativo: "She ___ like the movie."', 'She ___ like the movie.', "didn't", ["didn't", 'did not']),
          TR('¿Viste la película?', 'Did you see the movie?', ['Did you see the movie', 'Did you watch the movie']),
          RO('Ordena: "¿La llamaste?"', 'Did you call her', ['her', 'Did', 'call', 'you']),
          L(["I didn't go to work yesterday.", 'I go to work every day.', "She didn't call me."], "I didn't go to work yesterday."),
          SP('Did you have a good weekend?'),
        ],
      },
    ],
  },

  // ── Unidad 8 — Planes y futuro ────────────────────────────────────────────
  {
    U: 8, title: 'Planes y futuro', theme_color: '#00B894', icon: 'event_upcoming',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Demuestra el futuro: "going to" para planes, "will" para decisiones/predicciones, invitaciones (Let\'s / Why don\'t we) y expresiones de tiempo.',
    vocab: [
      { word: 'tomorrow', translation: 'mañana', pos: 'adverb' },
      { word: 'tonight', translation: 'esta noche', pos: 'adverb' },
      { word: 'next week', translation: 'la próxima semana', pos: 'phrase' },
      { word: 'soon', translation: 'pronto', pos: 'adverb' },
      { word: 'going to', translation: 'ir a (futuro)', pos: 'phrase' },
      { word: 'will', translation: 'futuro (-é/-á)', pos: 'verb' },
      { word: 'plan', translation: 'plan', pos: 'noun' },
      { word: 'maybe', translation: 'quizás', pos: 'adverb' },
      { word: 'busy', translation: 'ocupado', pos: 'adjective' },
      { word: 'free', translation: 'libre', pos: 'adjective' },
      { word: 'meet', translation: 'encontrarse / reunirse', pos: 'verb' },
      { word: 'visit', translation: 'visitar', pos: 'verb' },
      { word: 'party', translation: 'fiesta', pos: 'noun' },
      { word: 'holiday', translation: 'vacaciones / día festivo', pos: 'noun' },
    ],
    lessons: [
      {
        title: 'Voy a… (going to)', topic: 'going_to',
        description: 'be going to + verbo · planes · "I\'m going to study"',
        items: [
          R('Completa: "I ___ going to study."', ['am', 'is', 'are'], 'am'),
          R('Completa: "We are going to ___ a movie."', ['watch', 'watched', 'watching'], 'watch'),
          M('Empareja cada expresión de tiempo.', [['tomorrow', 'mañana'], ['tonight', 'esta noche'], ['next week', 'la próxima semana']]),
          CZ('Completa: "She is going ___ travel."', 'She is going ___ travel.', 'to'),
          TR('Voy a estudiar inglés.', 'I am going to study English.', ["I'm going to study English", 'I am going to study english']),
          WB('Arma la frase: "Van a visitarnos".', ['They', 'are', 'going', 'to', 'visit', 'us', 'go'], ['They', 'are', 'going', 'to', 'visit', 'us']),
          L(["I'm going to call you tonight.", 'I called you last night.', 'She is going to study.'], "I'm going to call you tonight."),
          SP("Tomorrow I'm going to visit my family."),
        ],
      },
      {
        title: 'Will (decisiones y predicciones)', topic: 'will_future',
        description: 'will + verbo · "I think it will rain", "I\'ll help you"',
        items: [
          R('Completa: "I think it ___ rain."', ['will', 'going', 'is'], 'will'),
          R('Completa: "I\'ll ___ you tomorrow."', ['call', 'called', 'calling'], 'call'),
          R('"will" se usa para hablar del…', ['futuro', 'pasado', 'ayer'], 'futuro'),
          CZ('Completa: "I ___ help you."', 'I ___ help you.', 'will'),
          TR('Te ayudaré.', 'I will help you.', ["I'll help you", 'I will help you']),
          RO('Ordena: "Ella será famosa".', 'She will be famous', ['famous', 'She', 'be', 'will']),
          L(['It will be sunny tomorrow.', 'It was sunny yesterday.', 'It is raining now.'], 'It will be sunny tomorrow.'),
          SP('I think I will travel next year.'),
        ],
      },
      {
        title: 'Hacer planes e invitar', topic: 'plans_invitations',
        description: "Let's… · Why don't we…? · Would you like to…?",
        items: [
          R('Completa: "___ go to the cinema!"', ["Let's", 'Let', 'Lets'], "Let's"),
          R("Completa: \"Why don't ___ meet at six?\"", ['we', 'us', 'our'], 'we'),
          M('Empareja la frase con su sentido.', [["Let's go", 'Vamos'], ['Would you like…?', '¿Te gustaría…?'], ['Maybe', 'Quizás']]),
          CZ('Completa: "Would you ___ to come?"', 'Would you ___ to come?', 'like'),
          TR('¿Te gustaría tomar un café?', 'Would you like to have a coffee?', ['Would you like a coffee', 'Would you like to have a coffee', 'Would you like to have coffee']),
          WB('Arma la frase: "Encontrémonos en el parque".', ["Let's", 'meet', 'at', 'the', 'park', 'go'], ["Let's", 'meet', 'at', 'the', 'park']),
          L(["Why don't we go to the beach?", "Let's stay at home.", 'We went to the beach.'], "Why don't we go to the beach?"),
          SP("Let's have dinner together tonight."),
        ],
      },
      {
        title: 'Cuándo (tiempo futuro)', topic: 'future_time',
        description: 'tomorrow, tonight, next week, soon · "See you tomorrow"',
        items: [
          R('Completa: "See you ___."', ['next week', 'last week', 'yesterday'], 'next week'),
          R('Completa: "I\'m busy ___."', ['tonight', 'ago', 'last night'], 'tonight'),
          R('"soon" significa…', ['pronto', 'ayer', 'nunca'], 'pronto'),
          CZ('Completa: "The party is ___ Saturday."', 'The party is ___ Saturday.', 'on'),
          TR('Nos vemos mañana.', 'See you tomorrow.', ['See you tomorrow']),
          RO('Ordena: "Estoy libre la próxima semana".', 'I am free next week', ['free', 'I', 'week', 'am', 'next']),
          L(['The meeting is next Monday.', 'The meeting was last Monday.', 'We meet every day.'], 'The meeting is next Monday.'),
          SP("Next weekend I'm going to relax."),
        ],
      },
    ],
  },

  // ── Unidad 9 — De viaje ───────────────────────────────────────────────────
  {
    U: 9, title: 'De viaje', theme_color: '#0984E3', icon: 'flight',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Demuestra el inglés de viaje: transporte, direcciones (turn left/right, go straight), hotel/aeropuerto y pedir ayuda con can/could.',
    vocab: [
      { word: 'airport', translation: 'aeropuerto', pos: 'noun' },
      { word: 'train', translation: 'tren', pos: 'noun' },
      { word: 'bus', translation: 'autobús', pos: 'noun' },
      { word: 'ticket', translation: 'boleto / billete', pos: 'noun' },
      { word: 'station', translation: 'estación', pos: 'noun' },
      { word: 'map', translation: 'mapa', pos: 'noun' },
      { word: 'left', translation: 'izquierda', pos: 'noun' },
      { word: 'right', translation: 'derecha', pos: 'noun' },
      { word: 'straight', translation: 'recto / derecho', pos: 'adverb' },
      { word: 'hotel', translation: 'hotel', pos: 'noun' },
      { word: 'reservation', translation: 'reserva', pos: 'noun' },
      { word: 'luggage', translation: 'equipaje', pos: 'noun' },
      { word: 'passport', translation: 'pasaporte', pos: 'noun' },
      { word: 'arrive', translation: 'llegar', pos: 'verb' },
    ],
    lessons: [
      {
        title: 'Transporte', topic: 'transport',
        description: 'airport, train, bus, ticket, station · "I take the bus"',
        items: [
          M('Empareja cada palabra con su traducción.', [['airport', 'aeropuerto'], ['train', 'tren'], ['ticket', 'boleto']]),
          R('Completa: "I take the ___ to work."', ['bus', 'book', 'bed'], 'bus'),
          R('Una "station" es donde tomas un…', ['train', 'dog', 'meal'], 'train'),
          CZ('Completa: "I need a ___ to Madrid."', 'I need a ___ to Madrid.', 'ticket'),
          TR('El tren llega a las ocho.', 'The train arrives at eight.', ['The train arrives at 8', 'The train arrives at eight']),
          WB('Arma la pregunta: "¿Dónde está la parada del autobús?".', ['Where', 'is', 'the', 'bus', 'stop', 'are'], ['Where', 'is', 'the', 'bus', 'stop']),
          L(['The next train leaves at nine.', 'The bus arrives at ten.', 'The train left at eight.'], 'The next train leaves at nine.'),
          SP('I usually travel by bus.'),
        ],
      },
      {
        title: 'Direcciones', topic: 'directions',
        description: 'turn left/right, go straight · "How do I get to…?"',
        items: [
          R('Completa: "Turn ___ at the corner."', ['left', 'food', 'ticket'], 'left'),
          R('Completa: "Go ___ for two blocks."', ['straight', 'sit', 'slow'], 'straight'),
          M('Empareja cada dirección.', [['left', 'izquierda'], ['right', 'derecha'], ['straight', 'recto']]),
          CZ('Completa: "___ do I get to the station?"', '___ do I get to the station?', 'How'),
          TR('Gira a la derecha.', 'Turn right.', ['Turn right']),
          RO('Ordena: "Sigue recto y gira a la izquierda".', 'Go straight and turn left', ['straight', 'Go', 'turn', 'left', 'and']),
          L(['Turn right at the bank.', 'Turn left at the bank.', 'Go straight ahead.'], 'Turn right at the bank.'),
          SP('Excuse me, how do I get to the museum?'),
        ],
      },
      {
        title: 'En el hotel y el aeropuerto', topic: 'hotel_airport',
        description: 'reservation, passport, luggage · "I\'d like a room"',
        items: [
          R('Completa: "I have a ___ for two nights."', ['reservation', 'river', 'recipe'], 'reservation'),
          R('Completa: "Show your ___ at the airport."', ['passport', 'pasta', 'paper'], 'passport'),
          M('Empareja cada palabra con su traducción.', [['hotel', 'hotel'], ['luggage', 'equipaje'], ['passport', 'pasaporte']]),
          CZ("Completa: \"I'd ___ a single room, please.\"", "I'd ___ a single room, please.", 'like'),
          TR('¿Dónde está mi equipaje?', 'Where is my luggage?', ['Where is my luggage', "Where's my luggage"]),
          WB('Arma la frase: "Quisiera registrarme, por favor".', ["I'd", 'like', 'to', 'check', 'in', 'please', 'out'], ["I'd", 'like', 'to', 'check', 'in', 'please']),
          L(['Your room is on the third floor.', 'Your room is on the first floor.', 'The hotel is full.'], 'Your room is on the third floor.'),
          SP("I'd like a room with a view, please."),
        ],
      },
      {
        title: 'Pedir ayuda (can / could)', topic: 'requests',
        description: 'Can I…? · Could you…? · pedidos educados',
        items: [
          R('Completa: "___ you help me, please?"', ['Could', 'Did', 'Was'], 'Could'),
          R('Completa: "Can I ___ a question?"', ['ask', 'eat', 'run'], 'ask'),
          R('"Could you…?" es una forma…', ['educada', 'grosera', 'pasada'], 'educada'),
          CZ('Completa: "___ I have the bill, please?"', '___ I have the bill, please?', 'Can'),
          TR('¿Podrías ayudarme?', 'Could you help me?', ['Can you help me', 'Could you help me']),
          RO('Ordena: "¿Puedes llamar un taxi?"', 'Can you call a taxi', ['you', 'Can', 'taxi', 'a', 'call']),
          L(['Could you speak more slowly, please?', 'Can you speak louder, please?', "I don't understand you."], 'Could you speak more slowly, please?'),
          SP('Excuse me, could you help me, please?'),
        ],
      },
    ],
  },

  // ── Unidad 10 — Comer fuera y comprar ─────────────────────────────────────
  {
    U: 10, title: 'Comer fuera y comprar', theme_color: '#E17055', icon: 'restaurant',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Demuestra el inglés transaccional: pedir en un restaurante (would like), cantidades (some/any, much/many), comprar y dinero, y comparativos.',
    vocab: [
      { word: 'menu', translation: 'menú', pos: 'noun' },
      { word: 'order', translation: 'pedir / orden', pos: 'verb' },
      { word: 'bill', translation: 'cuenta', pos: 'noun' },
      { word: 'waiter', translation: 'mesero', pos: 'noun' },
      { word: 'dish', translation: 'plato', pos: 'noun' },
      { word: 'drink', translation: 'bebida / beber', pos: 'noun' },
      { word: 'expensive', translation: 'caro', pos: 'adjective' },
      { word: 'cheap', translation: 'barato', pos: 'adjective' },
      { word: 'money', translation: 'dinero', pos: 'noun' },
      { word: 'change', translation: 'cambio / vuelto', pos: 'noun' },
      { word: 'bottle', translation: 'botella', pos: 'noun' },
      { word: 'cup', translation: 'taza', pos: 'noun' },
      { word: 'delicious', translation: 'delicioso', pos: 'adjective' },
      { word: 'size', translation: 'talla / tamaño', pos: 'noun' },
    ],
    lessons: [
      {
        title: 'En el restaurante', topic: 'restaurant',
        description: 'menu, order, bill · "Can I have…?", "I\'d like…"',
        items: [
          M('Empareja cada palabra con su traducción.', [['menu', 'menú'], ['bill', 'cuenta'], ['waiter', 'mesero']]),
          R('Completa: "Can I have the ___, please?"', ['menu', 'moon', 'map'], 'menu'),
          R('Completa: "I\'d like to ___ a pizza."', ['order', 'open', 'owe'], 'order'),
          CZ("Completa: \"I'd ___ a coffee, please.\"", "I'd ___ a coffee, please.", 'like'),
          TR('La cuenta, por favor.', 'The bill, please.', ['The bill please', 'The check please']),
          WB('Arma la pregunta: "¿Me puede traer el menú, por favor?".', ['Can', 'I', 'have', 'the', 'menu', 'please', 'bill'], ['Can', 'I', 'have', 'the', 'menu', 'please']),
          L(['Would you like something to drink?', 'Would you like to order now?', 'Here is your bill.'], 'Would you like something to drink?'),
          SP("I'd like a table for two, please."),
        ],
      },
      {
        title: 'Comida y cantidades', topic: 'quantities',
        description: 'some/any, much/many · "a bottle of water"',
        items: [
          R('Completa: "I don\'t have ___ money."', ['any', 'some', 'many'], 'any'),
          R('Completa: "There are ___ apples."', ['some', 'much', 'a'], 'some'),
          R('Completa: "How ___ water do you want?"', ['much', 'many', 'old'], 'much'),
          CZ('Completa: "How ___ people are coming?"', 'How ___ people are coming?', 'many'),
          TR('Quiero una botella de agua.', 'I want a bottle of water.', ['I want a bottle of water', "I'd like a bottle of water"]),
          RO('Ordena: "No hay leche".', "There isn't any milk", ["isn't", 'There', 'milk', 'any']),
          L(['We need some bread and a little cheese.', "We don't have any bread.", 'I want a lot of coffee.'], 'We need some bread and a little cheese.'),
          SP('Can I have a cup of tea, please?'),
        ],
      },
      {
        title: 'Comprar y dinero', topic: 'shopping_money',
        description: 'How much…? · expensive/cheap · "I can\'t buy it"',
        items: [
          R('Completa: "How ___ is this shirt?"', ['much', 'many', 'old'], 'much'),
          R('Completa: "It\'s too ___. I can\'t buy it."', ['expensive', 'happy', 'fast'], 'expensive'),
          M('Empareja cada palabra con su traducción.', [['expensive', 'caro'], ['cheap', 'barato'], ['money', 'dinero']]),
          CZ('Completa: "Can I pay ___ card?"', 'Can I pay ___ card?', 'by'),
          TR('¿Cuánto cuesta?', 'How much is it?', ['How much is it', 'How much does it cost']),
          WB('Arma la frase: "Estos zapatos son demasiado caros".', ['These', 'shoes', 'are', 'too', 'expensive', 'cheap'], ['These', 'shoes', 'are', 'too', 'expensive']),
          L(['That will be ten dollars, please.', 'That is twenty dollars.', "It's free today."], 'That will be ten dollars, please.'),
          SP('How much does this cost, please?'),
        ],
      },
      {
        title: 'Comparar (comparativos)', topic: 'comparatives',
        description: 'cheaper, bigger, more expensive, better · than',
        items: [
          R('Completa: "This bag is ___ than that one."', ['cheaper', 'cheap', 'cheapest'], 'cheaper'),
          R('Completa: "Tea is ___ than coffee here."', ['more expensive', 'expensiver', 'most expensive'], 'more expensive'),
          R('"bigger" compara…', ['dos cosas', 'muchas cosas', 'nada'], 'dos cosas'),
          CZ('Completa (good → mejor): "This phone is ___ than mine."', 'This phone is ___ than mine.', 'better'),
          TR('Es más barato.', 'It is cheaper.', ["It's cheaper", 'It is cheaper']),
          RO('Ordena: "Este es mejor".', 'This one is better', ['better', 'This', 'is', 'one']),
          L(['The blue shirt is cheaper than the red one.', 'The red shirt is the cheapest.', 'Both shirts are expensive.'], 'The blue shirt is cheaper than the red one.'),
          SP('I think this restaurant is better.'),
        ],
      },
    ],
  },

  // ── Unidad 11 — Personas y descripciones ──────────────────────────────────
  {
    U: 11, title: 'Personas y descripciones', theme_color: '#A55EEA', icon: 'face',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Describe personas y lugares: apariencia, personalidad/emociones, presente continuo (lo que pasa ahora) y superlativos.',
    vocab: [
      { word: 'tall', translation: 'alto', pos: 'adjective' },
      { word: 'short', translation: 'bajo / corto', pos: 'adjective' },
      { word: 'hair', translation: 'cabello', pos: 'noun' },
      { word: 'eyes', translation: 'ojos', pos: 'noun' },
      { word: 'kind', translation: 'amable', pos: 'adjective' },
      { word: 'funny', translation: 'gracioso', pos: 'adjective' },
      { word: 'friendly', translation: 'amistoso', pos: 'adjective' },
      { word: 'tired', translation: 'cansado', pos: 'adjective' },
      { word: 'worried', translation: 'preocupado', pos: 'adjective' },
      { word: 'wearing', translation: 'llevando puesto', pos: 'verb' },
      { word: 'best', translation: 'el mejor', pos: 'adjective' },
      { word: 'tallest', translation: 'el más alto', pos: 'adjective' },
      { word: 'beautiful', translation: 'hermoso', pos: 'adjective' },
      { word: 'young', translation: 'joven', pos: 'adjective' },
    ],
    lessons: [
      {
        title: 'Apariencia', topic: 'appearance',
        description: 'tall, short, hair, eyes · "She has long hair"',
        items: [
          M('Empareja cada palabra con su traducción.', [['tall', 'alto'], ['short', 'bajo'], ['hair', 'cabello']]),
          R('Completa: "She ___ long hair."', ['has', 'is', 'do'], 'has'),
          R('Completa: "He is very ___."', ['tall', 'table', 'talk'], 'tall'),
          CZ('Completa: "He has blue ___."', 'He has blue ___.', 'eyes'),
          TR('Ella tiene el cabello largo.', 'She has long hair.', ['She has long hair']),
          WB('Arma la frase: "Mi hermano es alto y delgado".', ['My', 'brother', 'is', 'tall', 'and', 'thin', 'short'], ['My', 'brother', 'is', 'tall', 'and', 'thin']),
          L(['She has short brown hair.', 'She has long blonde hair.', 'He has blue eyes.'], 'She has short brown hair.'),
          SP('My best friend is tall and friendly.'),
        ],
      },
      {
        title: 'Personalidad y emociones', topic: 'personality_feelings',
        description: 'kind, funny, tired, worried · "She is very kind"',
        items: [
          M('Empareja cada palabra con su traducción.', [['kind', 'amable'], ['funny', 'gracioso'], ['tired', 'cansado']]),
          R('Completa: "She is very ___. She always helps."', ['kind', 'cold', 'tall'], 'kind'),
          R('Completa: "I\'m ___ today. I slept badly."', ['tired', 'tall', 'fast'], 'tired'),
          CZ('Completa: "He is ___. He makes me laugh."', 'He is ___. He makes me laugh.', 'funny'),
          TR('Estoy preocupado.', 'I am worried.', ["I'm worried", 'I am worried']),
          RO('Ordena: "Ella es muy amistosa".', 'She is very friendly', ['friendly', 'She', 'very', 'is']),
          L(['My teacher is kind and patient.', 'My teacher is strict and serious.', 'My friend is very funny.'], 'My teacher is kind and patient.'),
          SP('My mother is funny and very kind.'),
        ],
      },
      {
        title: 'Ahora mismo (presente continuo)', topic: 'present_continuous',
        description: 'be + -ing · "She is reading", "They are working"',
        items: [
          R('Completa: "Look! She ___ reading."', ['is', 'are', 'am'], 'is'),
          R('Completa: "They ___ playing now."', ['are', 'is', 'am'], 'are'),
          R('Completa: "What are you ___?"', ['doing', 'do', 'did'], 'doing'),
          CZ('Completa (cook): "I am ___ dinner now."', 'I am ___ dinner now.', 'cooking'),
          TR('Está lloviendo.', 'It is raining.', ["It's raining", 'It is raining']),
          WB('Arma la frase: "Él está trabajando en este momento".', ['He', 'is', 'working', 'at', 'the', 'moment', 'work'], ['He', 'is', 'working', 'at', 'the', 'moment']),
          L(['The children are sleeping now.', 'The children played outside.', 'The baby is crying.'], 'The children are sleeping now.'),
          SP('Right now I am studying English.'),
        ],
      },
      {
        title: 'Lo más… (superlativos)', topic: 'superlatives',
        description: 'the best, the tallest, the most… · "the biggest park"',
        items: [
          R('Completa: "She is the ___ student in class."', ['best', 'better', 'good'], 'best'),
          R('Completa: "It\'s the ___ building in the city."', ['tallest', 'taller', 'tall'], 'tallest'),
          R('"the best" compara…', ['muchas cosas', 'dos cosas', 'nada'], 'muchas cosas'),
          CZ('Completa (big): "This is the ___ park in town."', 'This is the ___ park in town.', 'biggest'),
          TR('Es el día más feliz.', 'It is the happiest day.', ["It's the happiest day", 'It is the happiest day']),
          RO('Ordena: "Ella es la más alta".', 'She is the tallest', ['tallest', 'She', 'the', 'is']),
          L(['This is the most beautiful beach here.', 'This beach is very dirty.', 'That is the biggest city.'], 'This is the most beautiful beach here.'),
          SP('My city is the best place to live.'),
        ],
      },
    ],
  },

  // ── Unidad 12 — Salud, experiencias y consejos ────────────────────────────
  {
    U: 12, title: 'Salud, experiencias y consejos', theme_color: '#EB3B5A', icon: 'health_and_safety',
    checkpoint_description: 'Cronometrado · 4 habilidades · 80%. Habla de salud (el cuerpo, en el médico), da consejos con should, cuenta experiencias (Have you ever…? / I\'ve never…) y narra el pasado con ago/already.',
    vocab: [
      { word: 'head', translation: 'cabeza', pos: 'noun' },
      { word: 'stomach', translation: 'estómago', pos: 'noun' },
      { word: 'doctor', translation: 'médico', pos: 'noun' },
      { word: 'medicine', translation: 'medicina', pos: 'noun' },
      { word: 'sick', translation: 'enfermo', pos: 'adjective' },
      { word: 'healthy', translation: 'saludable', pos: 'adjective' },
      { word: 'rest', translation: 'descansar', pos: 'verb' },
      { word: 'exercise', translation: 'ejercicio / hacer ejercicio', pos: 'noun' },
      { word: 'ever', translation: 'alguna vez', pos: 'adverb' },
      { word: 'never', translation: 'nunca', pos: 'adverb' },
      { word: 'already', translation: 'ya', pos: 'adverb' },
      { word: 'been', translation: 'estado / sido', pos: 'verb' },
      { word: 'advice', translation: 'consejo', pos: 'noun' },
      { word: 'hurt', translation: 'doler / lastimar', pos: 'verb' },
    ],
    lessons: [
      {
        title: 'El cuerpo y la salud', topic: 'body_health',
        description: 'head, stomach, doctor · "I have a headache"',
        items: [
          M('Empareja cada palabra con su traducción.', [['head', 'cabeza'], ['stomach', 'estómago'], ['doctor', 'médico']]),
          R('Completa: "I have a ___. My head hurts."', ['headache', 'homework', 'hat'], 'headache'),
          R('Completa: "You should see a ___."', ['doctor', 'door', 'dog'], 'doctor'),
          CZ('Completa: "I feel ___. I need to rest."', 'I feel ___. I need to rest.', 'sick'),
          TR('Me duele el estómago.', 'My stomach hurts.', ['My stomach hurts', 'I have a stomachache']),
          WB('Arma la frase: "Me duele la garganta".', ['I', 'have', 'a', 'sore', 'throat', 'head'], ['I', 'have', 'a', 'sore', 'throat']),
          L(['She has a fever and a cough.', 'She feels great today.', 'He has a headache.'], 'She has a fever and a cough.'),
          SP("I don't feel well today."),
        ],
      },
      {
        title: 'Consejos (should)', topic: 'should_advice',
        description: 'should / shouldn\'t · "You should rest"',
        items: [
          R('Completa: "You ___ drink more water."', ['should', 'are', 'did'], 'should'),
          R('Completa: "You ___ smoke. It\'s bad."', ["shouldn't", 'should', 'will'], "shouldn't"),
          R('"should" sirve para…', ['dar consejos', 'contar el pasado', 'pedir comida'], 'dar consejos'),
          CZ('Completa: "You ___ rest and sleep more."', 'You ___ rest and sleep more.', 'should'),
          TR('Deberías ver a un médico.', 'You should see a doctor.', ['You should see a doctor']),
          RO('Ordena: "Deberías comer más verduras".', 'You should eat more vegetables', ['should', 'You', 'more', 'eat', 'vegetables']),
          L(['You should take this medicine twice a day.', "You shouldn't eat sugar.", 'You should drink more water.'], 'You should take this medicine twice a day.'),
          SP('You should exercise three times a week.'),
        ],
      },
      {
        title: 'Experiencias (Have you ever…?)', topic: 'present_perfect_intro',
        description: 'have/has + been/done · ever, never · "Have you ever…?"',
        items: [
          R('Completa: "___ you ever been to London?"', ['Have', 'Did', 'Are'], 'Have'),
          R('Completa: "I\'ve never ___ sushi."', ['eaten', 'ate', 'eat'], 'eaten'),
          R('Completa: "She has ___ to Paris."', ['been', 'being', 'be'], 'been'),
          CZ('Completa: "I have ___ seen that movie."', 'I have ___ seen that movie.', 'already'),
          TR('Nunca he estado en Japón.', 'I have never been to Japan.', ["I've never been to Japan", 'I have never been to Japan']),
          WB('Arma la pregunta: "¿Alguna vez probaste comida italiana?".', ['Have', 'you', 'ever', 'tried', 'Italian', 'food', 'eat'], ['Have', 'you', 'ever', 'tried', 'Italian', 'food']),
          L(['I have never been to the United States.', 'I have been to many countries.', 'I went to Canada last year.'], 'I have never been to the United States.'),
          SP('I have been to many countries.'),
        ],
      },
      {
        title: 'Contar una historia', topic: 'telling_story',
        description: 'ago / already · repaso del pasado · narrar',
        items: [
          R('Completa: "I finished it two hours ___."', ['ago', 'already', 'ever'], 'ago'),
          R('Completa: "We have ___ eaten."', ['already', 'ago', 'yesterday'], 'already'),
          M('Empareja cada palabra con su traducción.', [['ago', 'hace (tiempo)'], ['already', 'ya'], ['never', 'nunca']]),
          CZ('Completa: "They arrived an hour ___."', 'They arrived an hour ___.', 'ago'),
          TR('Ya he terminado.', 'I have already finished.', ["I've already finished", 'I have already finished']),
          RO('Ordena: "Ya he comido".', 'I have already eaten', ['already', 'I', 'eaten', 'have']),
          L(['We met two years ago.', 'We will meet next year.', 'They have already left.'], 'We met two years ago.'),
          SP('Last summer I visited my grandparents and we had a great time.'),
        ],
      },
    ],
  },
];
