-- 20260703120106_seed_tips_de_nl_a2.sql
-- Tips post-lección multi-curso (lote de_nl_a2). ADITIVA (no toca los tips en de mig
-- 057). content_tips es course-scoped → get_lesson_tip (mig 069, WHERE course_id=
-- jz_active_course()) devuelve sólo el del curso activo. Sin fuga multicurso.
begin;
insert into content_tips (id, course_id, unit_order, cefr_level, skill, type, topic, title, body, example) values
('694aa15c-918a-59c6-8cff-d91f62ed6396'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,7,'A2',$p$writing$p$,$p$gramatica$p$,$p$perfekt_haben$p$,$p$El participio siempre cierra la frase$p$,$p$El Perfekt se arma con «haben» conjugado en 2ª posición y el Partizip II AL FINAL, aunque queden palabras en medio. Los regulares hacen ge-…-t (machen → gemacht, kaufen → gekauft) y muchos irregulares ge-…-en (essen → gegessen, trinken → getrunken, sehen → gesehen).$p$,$p$Ich habe gestern Pizza gegessen. · Wir haben einen Kaffee getrunken. · Was hast du gemacht?$p$),
('6383c551-b379-56e4-b934-f70ad7f7e913'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,8,'A2',$p$reading$p$,$p$gramatica$p$,$p$futur_werden$p$,$p$El futuro más natural es el presente$p$,$p$Para hablar de mañana, los alemanes usan el PRESENTE con una marca temporal, y al ponerla delante el verbo salta a 2ª posición: «Morgen fahre ich…». También existe «werden + infinitivo» (con el infinitivo al final) para planes y predicciones. El verbo conjugado va SIEMPRE en 2ª posición.$p$,$p$Morgen fahre ich nach Berlin. · Nächste Woche besuche ich meine Oma. · Ich werde viel reisen.$p$),
('a5109a68-5ffe-5989-8528-422479c55e89'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,9,'A2',$p$writing$p$,$p$error_comun$p$,$p$perfekt_sein$p$,$p$Si te mueves, el Perfekt pide «sein»$p$,$p$Los verbos de movimiento o cambio de estado (gehen, fahren, fliegen, kommen, bleiben) forman el Perfekt con «sein», no con «haben». Truco: ¿cambiaste de lugar o de estado? Entonces «sein». Compara: compraste algo (haben) frente a fuiste a algún sitio (sein).$p$,$p$Ich bin nach Berlin gefahren. · Sie ist nach Rom geflogen. · Wir sind zu Hause geblieben. (pero: Ich habe ein Ticket gekauft.)$p$),
('30011d2e-6ead-5423-aae0-506bc7853b54'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,10,'A2',$p$reading$p$,$p$error_comun$p$,$p$comparativo$p$,$p$Para comparar se usa «als», nunca «wie»$p$,$p$El comparativo añade -er + «als»: billiger als, schneller als. Muchas vocales cortas se ponen Umlaut: groß → größer, alt → älter, jung → jünger. Y memoriza los rebeldes: gut → besser, viel → mehr, gern → lieber. Para la desigualdad jamás digas «wie».$p$,$p$Das Auto ist billiger als der Zug. · Berlin ist größer als München. · Ich trinke lieber Tee als Kaffee.$p$),
('65de7b38-26db-56c1-ac25-8612fd834b8e'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,11,'A2',$p$reading$p$,$p$gramatica$p$,$p$praeteritum_sein_haben$p$,$p$Para el pasado de «ser» y «tener», Präteritum$p$,$p$Aunque casi todo se cuenta en Perfekt, «sein» y «haben» prefieren el Präteritum para describir cómo eran las cosas: «war» (era/estaba) y «hatte» (tenía). Fíjate: la 1ª y la 3ª persona del singular son idénticas (ich war = er war).$p$,$p$Ich war müde. · Es war schön. · Sie hatte lange Haare. · Wir hatten kein Geld.$p$),
('2daf0db5-2d9e-5715-b42b-4e5a490666a8'::uuid,'20000000-0000-0000-0000-000000000005'::uuid,12,'A2',$p$speaking$p$,$p$gramatica$p$,$p$dolor_wehtun$p$,$p$Lo que te duele va en dativo$p$,$p$Con «wehtun» la parte del cuerpo es el sujeto y la persona dolida va en DATIVO: «Mir tut der Kopf weh» (me duele la cabeza). Si duelen varias cosas, el verbo va en plural: «Mir tun die Füße weh». Más fácil aún: «Ich habe Kopfschmerzen». Para aconsejar usa «Du solltest…».$p$,$p$Mir tut der Kopf weh. · Mir tun die Füße weh. · Ich habe Halsschmerzen. · Du solltest zum Arzt gehen.$p$),
('d18e6082-4101-567c-a3a7-7fbe9ffc4846'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,7,'A2',$p$writing$p$,$p$gramatica$p$,$p$perfectum_hebben$p$,$p$El pasado va en dos piezas: hebben + el verbo… al final$p$,$p$Para contar algo pasado usa «hebben» conjugado justo tras el sujeto y manda el participio (voltooid deelwoord) hasta el FINAL de la frase. Los regulares hacen ge-…-t/-d (gewerkt, gemaakt); muchos frecuentes son irregulares con ge-…-en (gegeten, gedronken, gezien, gedaan).$p$,$p$Ik heb gisteren gewerkt. · We hebben pizza gegeten. · Zij heeft hem gezien.$p$),
('62f06e0a-c37b-552f-b7d8-fc28c37fdc96'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,8,'A2',$p$speaking$p$,$p$gramatica$p$,$p$futuro_gaan$p$,$p$El futuro más natural: «gaan» + el infinitivo al final$p$,$p$En el día a día el neerlandés dice el futuro con «gaan» + infinitivo, y ese infinitivo cierra la frase: «Ik ga morgen reizen». «Zullen» suena a promesa o formal («Ik zal komen»), y con una marca de tiempo basta el presente con inversión: «Morgen werk ik».$p$,$p$Ik ga morgen reizen. · Ik zal je bellen. · Morgen werk ik thuis.$p$),
('878d4620-4c08-5496-b26d-10d1c50f9798'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,9,'A2',$p$writing$p$,$p$error_comun$p$,$p$perfectum_zijn$p$,$p$¿«heb» o «ben»? Los verbos de movimiento van con ZIJN$p$,$p$No todos los perfectos usan «hebben»: los verbos de movimiento o cambio de estado piden «zijn» (gaan, komen, blijven…). Contrasta la acción con objeto y el desplazamiento: «Ik heb een kaartje gekocht» pero «Ik ben naar Amsterdam gegaan».$p$,$p$Ik ben naar Amsterdam gegaan. · Zij is gekomen. · We zijn thuis gebleven.$p$),
('8b868a21-cdb9-5b9d-8739-ec9bb3c5014e'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,10,'A2',$p$reading$p$,$p$error_comun$p$,$p$comparativo_dan$p$,$p$Más barato… «dan», nunca «als»$p$,$p$El comparativo añade -er al adjetivo y la comparación se marca con «dan»: goedkoper dan, groter dan, duurder dan. Ojo con los irregulares (goed→beter, veel→meer, graag→liever). Si sabes alemán o inglés te saldrá «als/as», pero para la desigualdad el neerlandés SIEMPRE usa «dan».$p$,$p$Deze trui is goedkoper dan die jas. · Dit huis is groter dan het mijne. · Ik drink liever thee dan koffie.$p$),
('06df1131-e2f5-5416-8d6b-a585a01de3d1'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,11,'A2',$p$writing$p$,$p$gramatica$p$,$p$imperfectum_zijn$p$,$p$Describir el pasado: «was», «waren», «had», «hadden»$p$,$p$Para pintar cómo era algo no se usa el perfecto sino el imperfectum de zijn y hebben. De «zijn»: was (ik/hij/zij) y waren (wij/jullie/zij); de «hebben»: had y hadden. Sirven para estados, sensaciones y descripciones: «Ik was moe», «Het was leuk».$p$,$p$Ik was moe. · Het was heel leuk. · Zij had lang haar en we waren blij.$p$),
('7a2b5d37-98ac-536c-93d8-0497ffdd5608'::uuid,'20000000-0000-0000-0000-000000000006'::uuid,12,'A2',$p$speaking$p$,$p$cultura$p$,$p$pijn_klachten$p$,$p$El dolor se pega a la parte del cuerpo: «hoofdpijn»$p$,$p$En neerlandés el dolor de una zona suele ser UNA sola palabra: hoofd+pijn, buik+pijn, keel+pijn, y se dice con hebben («Ik heb hoofdpijn»). Si no, usa «doet pijn» (o «doen pijn» en plural): «Mijn rug doet pijn», «Mijn voeten doen pijn». Para aconsejar: «Je moet…» o «Je zou … moeten».$p$,$p$Ik heb keelpijn. · Mijn voeten doen pijn. · Je moet water drinken en rusten.$p$)
on conflict (id) do update set skill=excluded.skill, type=excluded.type, topic=excluded.topic, title=excluded.title, body=excluded.body, example=excluded.example;
commit;