-- CAUSA RAÍZ (otra superficie): el corrector NO ignora los acentos —verificado
-- contra jz_normalize/jz_grade—, así que un cloze cuya respuesta lleva acento
-- CASTIGABA a quien teclea sin él ("está"→"esta", "é"→"e", "garçom"→"garcom"),
-- que es justo lo que se escribe en móvil. Regla de oro: ante la duda, ACEPTAR.
-- Backfill determinista (cero autoría): a cada `accepted` de cada ítem cloze de
-- study_theory se le añade su forma SIN acento. Idempotente. NO toca el motor
-- FSRS, la economía, el gating ni la certificación: la prueba sigue siendo
-- FORMATIVA y el contenido de la teoría no cambia.

update public.study_theory set quiz = '[{"id": "u1q1", "type": "multiple_choice", "answer": "Muito prazer", "prompt": "Te presentan a alguien y quieres decir «mucho gusto». ¿Qué dices?", "options": ["Muito prazer", "Muito gosto", "Por favor"]}, {"id": "u1q2", "type": "multiple_choice", "answer": "é", "prompt": "Completa con la forma correcta: «Você ___ meu amigo.»", "options": ["é", "és", "sou"]}, {"id": "u1q3", "text": "Você ___ do Brasil?", "type": "cloze", "answer": "é", "prompt": "Escribe la forma correcta del verbo SER (1 palabra):", "accepted": ["é", "e"]}, {"id": "u1q4", "text": "Nós ___ estudantes.", "type": "cloze", "answer": "somos", "prompt": "Escribe la forma correcta del verbo SER para «nosotros» (1 palabra):", "accepted": ["somos"]}, {"id": "u1q5", "text": "Eu ___ a Maria. Prazer!", "type": "cloze", "answer": "sou", "prompt": "Escribe la forma correcta del verbo SER para «yo» (1 palabra):", "accepted": ["sou"]}]'::jsonb, updated_at = now() where id = '898ab79b-87ac-4d06-855d-03d97d7845cc';
update public.study_theory set quiz = '[{"id": "u4q1", "type": "multiple_choice", "answer": "Eu queria um copo de água.", "prompt": "Estás en un café y quieres pedir un agua. ¿Qué dices para pedir un VASO de agua?", "options": ["Eu queria um copo de água.", "Eu queria um vaso de água.", "Eu queria uma taça de flores."]}, {"id": "u4q2", "type": "multiple_choice", "answer": "Florero o maceta", "prompt": "¿Qué significa la palabra portuguesa «vaso»?", "options": ["Florero o maceta", "Vaso de beber", "Copa de vino"]}, {"id": "u4q3", "text": "Quanto ___ esta camiseta?", "type": "cloze", "answer": "custa", "prompt": "Completa la pregunta por el precio (verbo portugués, no español).", "accepted": ["custa", "é", "e"]}, {"id": "u4q4", "text": "Eu ___ um café, por favor.", "type": "cloze", "answer": "queria", "prompt": "Pide un café de la forma MÁS SUAVE y cortés (una palabra).", "accepted": ["queria"]}, {"id": "u4q5", "type": "multiple_choice", "answer": "uma taça de vinho", "prompt": "¿Cómo se dice «una copa de vino» en portugués?", "options": ["uma taça de vinho", "um copo de flores", "um prato de vinho"]}]'::jsonb, updated_at = now() where id = 'a74dc526-2479-47f5-95c8-496c63cc5293';
update public.study_theory set quiz = '[{"id": "u10q1", "type": "multiple_choice", "answer": "a sobremesa", "prompt": "¿Cómo se dice «el postre» en portugués?", "options": ["a sobremesa", "o troco", "a gorjeta"]}, {"id": "u10q2", "type": "multiple_choice", "answer": "Que está raro", "prompt": "Un brasileño prueba tu plato y dice: «Está esquisito». ¿Qué quiere decir?", "options": ["Que está raro", "Que está delicioso", "Que está frío"]}, {"id": "u10q3", "type": "multiple_choice", "answer": "Suele venir ya sumada en la cuenta", "prompt": "En Brasil, la «gorjeta» del 10%…", "options": ["Suele venir ya sumada en la cuenta", "Se paga siempre aparte y en efectivo", "No existe en los restaurantes"]}, {"id": "u10q4", "text": "O ___ trouxe o cardápio.", "type": "cloze", "answer": "garçom", "prompt": "Completa con la palabra para «el camarero».", "accepted": ["garçom", "garcom"]}, {"id": "u10q5", "text": "Paguei com uma nota de cinquenta e recebi o ___.", "type": "cloze", "answer": "troco", "prompt": "Completa con la palabra para «el cambio/vuelto».", "accepted": ["troco"]}]'::jsonb, updated_at = now() where id = '6986613a-968d-4493-81be-ce9fa7843ccf';
update public.study_theory set quiz = '[{"id": "u11q1", "type": "multiple_choice", "answer": "Ela está grávida.", "prompt": "Tu amiga espera un bebé. ¿Cómo lo dices en portugués?", "options": ["Ela está grávida.", "Ela está embaraçada.", "Ela está esquisita."]}, {"id": "u11q2", "type": "multiple_choice", "answer": "Los niños están jugando.", "prompt": "¿Qué significa «As crianças estão brincando»?", "options": ["Los niños están jugando.", "Los niños están saltando.", "Los niños están brindando."]}, {"id": "u11q3", "text": "Meu primo ___ muito engraçado.", "type": "cloze", "answer": "é", "prompt": "Completa con el verbo correcto: es una característica suya, no de hoy.", "accepted": ["é", "e"]}, {"id": "u11q4", "text": "Ele ___ cansado hoje.", "type": "cloze", "answer": "está", "prompt": "Completa con el verbo correcto: es un estado de hoy (ele).", "accepted": ["está", "esta"]}, {"id": "u11q5", "text": "Minha avó é muito ___.", "type": "cloze", "answer": "simpática", "prompt": "Haz concordar el adjetivo «simpático» con «Minha avó».", "accepted": ["simpática", "simpatica"]}]'::jsonb, updated_at = now() where id = '83f606e1-3df2-4cda-a867-cc058bf5d8cc';
update public.study_theory set quiz = '[{"id": "u13q1", "type": "multiple_choice", "answer": "brincava", "prompt": "Elige la forma correcta del imperfeito: «Quando eu era criança, eu ___ na rua.»", "options": ["brincava", "brincaba", "brinquei"]}, {"id": "u13q2", "type": "multiple_choice", "answer": "A gente tinha um cachorro", "prompt": "«A gente» va con verbo en 3ª persona del singular. ¿Cuál frase es correcta?", "options": ["A gente tinha um cachorro", "A gente tínhamos um cachorro", "A gente tiveram um cachorro"]}, {"id": "u13q3", "type": "multiple_choice", "answer": "Ontem eu fui ao cinema", "prompt": "Un hecho puntual y terminado. ¿Cuál frase es correcta para «ayer fui al cine»?", "options": ["Ontem eu fui ao cinema", "Ontem eu ia ao cinema", "Ontem eu vou ao cinema"]}, {"id": "u13q4", "text": "Antigamente nós ___ no interior.", "type": "cloze", "answer": "morávamos", "prompt": "Completa con el imperfeito del verbo «morar» en la 1ª persona del plural (nós).", "accepted": ["morávamos", "costumávamos morar", "moravamos", "costumavamos morar"]}, {"id": "u13q5", "text": "A minha escola ___ pequena e bonita.", "type": "cloze", "answer": "era", "prompt": "Completa con UNA palabra: el imperfeito del verbo «ser» en la 3ª persona del singular.", "accepted": ["era"]}]'::jsonb, updated_at = now() where id = '15a10124-e515-4bb1-9364-128af65bccc3';
update public.study_theory set quiz = '[{"id": "u18q1", "type": "multiple_choice", "answer": "melhor", "prompt": "Elige la forma correcta: «Este restaurante é ___ do que o outro.»", "options": ["melhor", "mais bom", "muito bom"]}, {"id": "u18q2", "type": "multiple_choice", "answer": "do", "prompt": "Completa: «São Paulo é a maior cidade ___ Brasil.»", "options": ["do", "no", "em"]}, {"id": "u18q3", "text": "Meu apartamento é ___ do que o seu.", "type": "cloze", "answer": "maior", "prompt": "Escribe el comparativo irregular de «grande» (una palabra).", "accepted": ["maior"]}, {"id": "u18q4", "text": "Ela é tão inteligente ___ o irmão.", "type": "cloze", "answer": "quanto", "prompt": "Completa la comparación de igualdad (una palabra).", "accepted": ["quanto", "como"]}, {"id": "u18q5", "text": "Esse celular é ___: custa dez mil reais.", "type": "cloze", "answer": "caríssimo", "prompt": "Escribe el superlativo absoluto de «caro» con el sufijo -íssimo (una palabra).", "accepted": ["caríssimo", "carissimo"]}]'::jsonb, updated_at = now() where id = '465a9ec8-b09c-4720-8781-dd11677d5a8e';
